"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import finetuningjob as components_finetuningjob
from typing import Optional


@dataclasses.dataclass
class CancelFineTuningJobRequest:
    fine_tuning_job_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'fine_tuning_job_id', 'style': 'simple', 'explode': False }})
    r"""The ID of the fine-tuning job to cancel."""
    



@dataclasses.dataclass
class CancelFineTuningJobResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    fine_tuning_job: Optional[components_finetuningjob.FineTuningJob] = dataclasses.field(default=None)
    r"""OK"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

