"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import createtranslationresponsejson as components_createtranslationresponsejson
from ...models.components import createtranslationresponseverbosejson as components_createtranslationresponseverbosejson
from typing import Optional, Union


@dataclasses.dataclass
class CreateTranslationResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    one_of: Optional[Union[components_createtranslationresponsejson.CreateTranslationResponseJSON, components_createtranslationresponseverbosejson.CreateTranslationResponseVerboseJSON]] = dataclasses.field(default=None)
    r"""OK"""
    

