"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import deleteassistantresponse as components_deleteassistantresponse
from typing import Optional


@dataclasses.dataclass
class DeleteAssistantRequest:
    assistant_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'assistant_id', 'style': 'simple', 'explode': False }})
    r"""The ID of the assistant to delete."""
    



@dataclasses.dataclass
class DeleteAssistantResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    delete_assistant_response: Optional[components_deleteassistantresponse.DeleteAssistantResponse] = dataclasses.field(default=None)
    r"""OK"""
    

