"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import deletemodelresponse as components_deletemodelresponse
from typing import Optional


@dataclasses.dataclass
class DeleteModelRequest:
    model: str = dataclasses.field(metadata={'path_param': { 'field_name': 'model', 'style': 'simple', 'explode': False }})
    r"""The model to delete"""
    



@dataclasses.dataclass
class DeleteModelResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    delete_model_response: Optional[components_deletemodelresponse.DeleteModelResponse] = dataclasses.field(default=None)
    r"""OK"""
    

