"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import deletemodelresponse as shared_deletemodelresponse
from typing import Optional


@dataclasses.dataclass
class DeleteModelRequest:
    
    model: str = dataclasses.field(metadata={'path_param': { 'field_name': 'model', 'style': 'simple', 'explode': False }})
    r"""The model to delete"""
    

@dataclasses.dataclass
class DeleteModelResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    delete_model_response: Optional[shared_deletemodelresponse.DeleteModelResponse] = dataclasses.field(default=None)
    r"""OK"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    