"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import assistantobject as components_assistantobject
from typing import Optional


@dataclasses.dataclass
class GetAssistantRequest:
    assistant_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'assistant_id', 'style': 'simple', 'explode': False }})
    r"""The ID of the assistant to retrieve."""
    



@dataclasses.dataclass
class GetAssistantResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    assistant_object: Optional[components_assistantobject.AssistantObject] = dataclasses.field(default=None)
    r"""OK"""
    

