"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import runstepobject as components_runstepobject
from typing import Optional


@dataclasses.dataclass
class GetRunStepRequest:
    run_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'run_id', 'style': 'simple', 'explode': False }})
    r"""The ID of the run to which the run step belongs."""
    step_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'step_id', 'style': 'simple', 'explode': False }})
    r"""The ID of the run step to retrieve."""
    thread_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'thread_id', 'style': 'simple', 'explode': False }})
    r"""The ID of the thread to which the run and run step belongs."""
    



@dataclasses.dataclass
class GetRunStepResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    run_step_object: Optional[components_runstepobject.RunStepObject] = dataclasses.field(default=None)
    r"""OK"""
    

