"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .functionobject import FunctionObject
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from gpt import utils

class AssistantToolsFunctionType(str, Enum):
    r"""The type of tool being defined: `function`"""
    FUNCTION = 'function'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AssistantToolsFunction:
    function: FunctionObject = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('function') }})
    type: AssistantToolsFunctionType = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('type') }})
    r"""The type of tool being defined: `function`"""
    

