"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from gpt import utils

class Object(str, Enum):
    r"""The object type, which is always `assistant.file`."""
    ASSISTANT_FILE = 'assistant.file'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AssistantFileObject:
    r"""A list of [Files](/docs/api-reference/files) attached to an `assistant`."""
    assistant_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('assistant_id') }})
    r"""The assistant ID that the file is attached to."""
    created_at: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('created_at') }})
    r"""The Unix timestamp (in seconds) for when the assistant file was created."""
    id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id') }})
    r"""The identifier, which can be referenced in API endpoints."""
    object: Object = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('object') }})
    r"""The object type, which is always `assistant.file`."""
    

