"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class One(str, Enum):
    r"""`none` means the model will not call a function and instead generates a message. `auto` means the model can pick between generating a message or calling a function."""
    NONE = 'none'
    AUTO = 'auto'
