"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from enum import Enum
from typing import Optional, Union


@dataclasses.dataclass
class CreateTranslationRequestFile:
    content: bytes = dataclasses.field(metadata={'multipart_form': { 'content': True }})
    file_name: str = dataclasses.field(metadata={'multipart_form': { 'field_name': 'file' }})
    


class CreateTranslationRequest2(str, Enum):
    WHISPER_1 = 'whisper-1'


@dataclasses.dataclass
class CreateTranslationRequest:
    file: CreateTranslationRequestFile = dataclasses.field(metadata={'multipart_form': { 'file': True }})
    r"""The audio file object (not file name) translate, in one of these formats: flac, mp3, mp4, mpeg, mpga, m4a, ogg, wav, or webm."""
    model: Union[str, CreateTranslationRequest2] = dataclasses.field(metadata={'multipart_form': { 'field_name': 'model' }})
    r"""ID of the model to use. Only `whisper-1` is currently available."""
    prompt: Optional[str] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'prompt' }})
    r"""An optional text to guide the model's style or continue a previous audio segment. The [prompt](/docs/guides/speech-to-text/prompting) should be in English."""
    response_format: Optional[str] = dataclasses.field(default='json', metadata={'multipart_form': { 'field_name': 'response_format' }})
    r"""The format of the transcript output, in one of these options: `json`, `text`, `srt`, `verbose_json`, or `vtt`."""
    temperature: Optional[float] = dataclasses.field(default=0, metadata={'multipart_form': { 'field_name': 'temperature' }})
    r"""The sampling temperature, between 0 and 1. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. If set to 0, the model will use [log probability](https://en.wikipedia.org/wiki/Log_probability) to automatically increase the temperature until certain thresholds are hit."""
    

