"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .embedding import Embedding
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from gpt import utils
from typing import List

class CreateEmbeddingResponseObject(str, Enum):
    r"""The object type, which is always \\"list\\"."""
    LIST = 'list'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Usage:
    r"""The usage information for the request."""
    prompt_tokens: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('prompt_tokens') }})
    r"""The number of tokens used by the prompt."""
    total_tokens: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('total_tokens') }})
    r"""The total number of tokens used by the request."""
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreateEmbeddingResponse:
    data: List[Embedding] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('data') }})
    r"""The list of embeddings generated by the model."""
    model: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('model') }})
    r"""The name of the model used to generate the embedding."""
    object: CreateEmbeddingResponseObject = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('object') }})
    r"""The object type, which is always \\"list\\"."""
    usage: Usage = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('usage') }})
    r"""The usage information for the request."""
    

