"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from gpt import utils

class Level(str, Enum):
    INFO = 'info'
    WARN = 'warn'
    ERROR = 'error'

class FineTuningJobEventObject(str, Enum):
    FINE_TUNING_JOB_EVENT = 'fine_tuning.job.event'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class FineTuningJobEvent:
    r"""Fine-tuning job event object"""
    created_at: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('created_at') }})
    id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id') }})
    level: Level = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('level') }})
    message: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('message') }})
    object: FineTuningJobEventObject = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('object') }})
    

