"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .finetune import FineTune
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from gpt import utils
from typing import List

class ListFineTunesResponseObject(str, Enum):
    LIST = 'list'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ListFineTunesResponse:
    data: List[FineTune] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('data') }})
    object: ListFineTunesResponseObject = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('object') }})
    

