"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from gpt import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ImageFile:
    file_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('file_id') }})
    r"""The [File](/docs/api-reference/files) ID of the image in the message content."""
    


class MessageContentImageFileObjectType(str, Enum):
    r"""Always `image_file`."""
    IMAGE_FILE = 'image_file'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class MessageContentImageFileObject:
    r"""References an image [File](/docs/api-reference/files) in the content of a message."""
    image_file: ImageFile = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('image_file') }})
    type: MessageContentImageFileObjectType = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('type') }})
    r"""Always `image_file`."""
    

