"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from gpt import utils

class ModelObject(str, Enum):
    r"""The object type, which is always \\"model\\"."""
    MODEL = 'model'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Model:
    r"""Describes an OpenAI model offering that can be used with the API."""
    created: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('created') }})
    r"""The Unix timestamp (in seconds) when the model was created."""
    id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id') }})
    r"""The model identifier, which can be referenced in the API endpoints."""
    object: ModelObject = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('object') }})
    r"""The object type, which is always \\"model\\"."""
    owned_by: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('owned_by') }})
    r"""The organization that owns the model."""
    

