"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from gpt import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class MessageCreation:
    message_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('message_id') }})
    r"""The ID of the message that was created by this run step."""
    


class RunStepDetailsMessageCreationObjectType(str, Enum):
    r"""Always `message_creation`."""
    MESSAGE_CREATION = 'message_creation'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class RunStepDetailsMessageCreationObject:
    r"""Details of the message creation by the run step."""
    message_creation: MessageCreation = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('message_creation') }})
    type: RunStepDetailsMessageCreationObjectType = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('type') }})
    r"""Always `message_creation`."""
    

