"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from gpt import utils


@dataclasses.dataclass
class Retrieval:
    r"""For now, this is always going to be an empty object."""
    


class RunStepDetailsToolCallsRetrievalObjectType(str, Enum):
    r"""The type of tool call. This is always going to be `retrieval` for this type of tool call."""
    RETRIEVAL = 'retrieval'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class RunStepDetailsToolCallsRetrievalObject:
    id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id') }})
    r"""The ID of the tool call object."""
    retrieval: Retrieval = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('retrieval') }})
    r"""For now, this is always going to be an empty object."""
    type: RunStepDetailsToolCallsRetrievalObjectType = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('type') }})
    r"""The type of tool call. This is always going to be `retrieval` for this type of tool call."""
    

